### ISSUE TITLE
`./waf configure` should check for liblo

### ISSUE THREAD

**Issue by rknLA** [monome/serialosc#23]

**Comment by simonvanderveldt** [comment]
@rknLA What kind of behaviour are you seeing exactly? Because there is already a check for liblo in the `wscript`, see https://github.com/monome/serialosc/blob/2b8d636b6bda76122238fe35f7c0ab727ed8d409/wscript#L60 and https://github.com/monome/serialosc/blob/2b8d636b6bda76122238fe35f7c0ab727ed8d409/wscript#L193

The `./waf configure` output for me is as follows:
```
./waf configure --disable-zeroconf                           
Setting top to                           : /home/simon/src/forks/serialosc 
Setting out to                           : /home/simon/src/forks/serialosc/build 

Checking for 'gcc' (C compiler)          : /usr/bin/gcc 

Checking for working poll()              : yes 
Checking for libudev                     : yes 
Checking for libmonome                   : yes 
Checking for liblo                       : yes 
Checking for libuv                       : yes 
Checking for function strdup             : yes 
Checking for function _strdup            : not found 
Checking for function strndup            : yes 
Checking for function strcasecmp         : yes 
Checking for header unistd.h             : yes 
Checking for library dl                  : yes 
```

**Comment by rknLA** [comment]
I'll need to try to recompile things to see what the problem was.  It may have been a linker error, rather than a waf error.

**Comment by tehn** [comment]
checked this just now and it worked fine. post some details if you want to reopen the issue
