### ISSUE TITLE
serialosc won't compile on linux

### ISSUE THREAD

**Issue by murrayfoster** [monome/serialosc#9]
serialosc won't compile on linux.
gcc version 4.5.4 (Gentoo 4.5.4 p1.0, pie-0.4.7)

$ ./waf build  
Waf: Entering directory `/home/mfoster/serialosc_current/build'
[ 1/16] c: src/platform/posix.c -> build/src/platform/posix.c.2.o
[ 2/16] c: src/supervisor/posix.c -> build/src/supervisor/posix.c.2.o
[ 3/16] c: src/platform/linux.c -> build/src/platform/linux.c.2.o
[ 4/16] c: src/detector/libudev.c -> build/src/detector/libudev.c.2.o
[ 5/16] c: src/zeroconf/not_darwin.c -> build/src/zeroconf/not_darwin.c.2.o
../src/detector/libudev.c: In function 'send_connect':
../src/detector/libudev.c:44:3: error: unknown field 'connection' specified in initializer
../src/detector/libudev.c:44:3: error: unknown field 'devnode' specified in initializer
cc1: warnings being treated as errors
../src/detector/libudev.c:44:3: error: missing braces around initializer
../src/detector/libudev.c:44:3: error: (near initialization for 'msg.<anonymous>.connection')
Waf: Leaving directory`/home/mfoster/serialosc_current/build'
Build failed
 -> task in 'serialoscd' failed (exit status 1): 
    {task 141779244: c libudev.c -> libudev.c.2.o}
['/usr/bin/gcc', '-std=c99', '-Wall', '-Werror', '-I/home/mfoster/serialosc_current/build', '-I/home/mfoster/serialosc_current', '-I/home/mfoster/serialosc_current/build/src/private', '-I/home/mfoster/serialosc_current/src/private', '../src/detector/libudev.c', '-c', '-o', 'src/detector/libudev.c.2.o']

**Comment by cyphunk** [comment]
my oh my.

**Comment by bonemurmurer** [comment]
@cyphunk i've since been able to get it to install, i think this is an old ticket that i filed and was never closed. thanks for the attention. howevere there IS a bug i found in libmonome which i submitted a fix for which i would love to see incorporated.. (nobody seems to look at the pull requests)

**Comment by cyphunk** [comment]
yeah guess they are just a small team. :/

**Comment by simonvanderveldt** [comment]
> @cyphunk i've since been able to get it to install, i think this is an old ticket that i filed and was never closed. thanks for the attention :). however there IS a bug i found in libmonome which i submitted a fix for which i would love to see incorporated.. (nobody seems to look at the pull requests)

@murrayfoster Just looking at old issues. Do you know if the fix to libmonome has been incorporated?
(the only one I could find was [this one](https://github.com/monome/libmonome/pull/40), but I don't know if that's the one you're talking about).

Apart from that I guess this issue can be closed since compiling serialosc works as it should, correct?

**Comment by murrayfoster** [comment]
@simonvanderveldt it's been incorporated, should have closed this out!
fixed.
